"use client";

import { saveStaffRevenueRate, saveStaffSensitivePermissions, type StaffPermission } from "@/features/members/server/sensitive-permissions";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function SensitivePermissionsWorkspace({ members, errorMessage, revenueRateAvailable }: { members: StaffPermission[]; errorMessage: string | null; revenueRateAvailable: boolean }) {
  const router = useRouter(); const [savingUserId, setSavingUserId] = useState<string | null>(null); const [message, setMessage] = useState("");
  async function save(member: StaffPermission, form: HTMLFormElement) { const data = new FormData(form); setSavingUserId(member.clerkUserId); setMessage(""); const permission = member.role === "admin" ? { ok: true as const } : await saveStaffSensitivePermissions({ clerkUserId: member.clerkUserId, propertyContacts: data.get("propertyContacts") === "on", unitAccess: data.get("unitAccess") === "on", consultationContacts: data.get("consultationContacts") === "on" }); const rate = revenueRateAvailable ? await saveStaffRevenueRate({ clerkUserId: member.clerkUserId, staffRevenueRate: String(data.get("staffRevenueRate") ?? "") }) : { ok: true as const }; setSavingUserId(null); setMessage(permission.ok && rate.ok ? (member.role === "admin" ? "관리자 기본 수수료 비율을 저장했습니다." : revenueRateAvailable ? "직원 권한과 기본 수수료 비율을 저장했습니다." : "직원 권한을 저장했습니다.") : permission.ok ? (rate.message ?? "기본 수수료 비율을 저장하지 못했습니다.") : (permission.message ?? "직원 권한을 저장하지 못했습니다.")); if (permission.ok && rate.ok) router.refresh(); }
  return <section className="max-w-4xl rounded-xl border border-[#e5e1db] bg-white p-5"><h2 className="font-extrabold">직원별 권한·기본 수수료</h2><p className="mt-1 text-sm text-[#655f59]">관리자가 직원별 기본 담당자 수수료 비율을 정하면, 새 계약 정산에 자동으로 채워집니다.</p>{errorMessage && <p className="mt-4 rounded-lg border border-[#e7c3ba] bg-[#fff7f4] px-3 py-2 text-xs text-[#a84438]">{errorMessage}</p>}{message && <p className="mt-4 rounded-lg bg-[#f5eee9] px-3 py-2 text-xs text-[#655f59]">{message}</p>}<div className="mt-5 space-y-3">{members.map((member) => member.role === "admin" ? <form key={member.clerkUserId} className="rounded-lg bg-[#faf8f4] p-4" onSubmit={(event) => { event.preventDefault(); void save(member, event.currentTarget); }}><div className="flex items-start justify-between gap-3"><div><p className="font-bold">관리자 계정</p><p className="mt-1 font-mono text-[11px] text-[#77736e]">{member.clerkUserId}</p></div><button disabled={savingUserId === member.clerkUserId || !revenueRateAvailable} className="rounded-lg bg-[#3e3a37] px-3 py-2 text-xs font-bold text-white disabled:opacity-60">{savingUserId === member.clerkUserId ? "저장 중…" : "비율 저장"}</button></div><label className="mt-4 block max-w-xs text-xs font-bold text-[#655f59]">관리자 담당자 수수료 비율 (%)<input className="field mt-2" defaultValue={member.staffRevenueRate} disabled={!revenueRateAvailable} inputMode="decimal" name="staffRevenueRate" /></label></form> : <form key={member.clerkUserId} className="rounded-lg border border-[#eeeae5] p-4" onSubmit={(event) => { event.preventDefault(); void save(member, event.currentTarget); }}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-bold">staff · {member.status === "active" ? "활성" : "비활성"}</p><p className="mt-1 font-mono text-[11px] text-[#77736e]">{member.clerkUserId}</p></div><button disabled={savingUserId === member.clerkUserId || member.status !== "active"} className="rounded-lg bg-[#3e3a37] px-3 py-2 text-xs font-bold text-white disabled:opacity-60">{savingUserId === member.clerkUserId ? "저장 중…" : "설정 저장"}</button></div><div className="mt-4 grid gap-2 sm:grid-cols-4">{[["propertyContacts", "임대인·세입자 연락처", member.propertyContacts], ["unitAccess", "세대 비밀번호·출입 정보", member.unitAccess], ["consultationContacts", "상담 고객 연락처", member.consultationContacts]].map(([name, label, checked]) => <label className="flex items-start gap-2 rounded-md bg-[#faf8f4] p-3 text-xs font-bold text-[#655f59]" key={name as string}><input className="mt-0.5" defaultChecked={checked as boolean} disabled={member.status !== "active"} name={name as string} type="checkbox" /><span>{label}</span></label>)}<label className="rounded-md bg-[#faf8f4] p-3 text-xs font-bold text-[#655f59]">담당자 수수료 비율 (%)<input className="field mt-2" defaultValue={member.staffRevenueRate} disabled={member.status !== "active" || !revenueRateAvailable} inputMode="decimal" name="staffRevenueRate" /></label></div></form>)}</div></section>;
}
