"use client";

import { saveStaffSensitivePermissions, type StaffPermission } from "@/features/members/server/sensitive-permissions";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function SensitivePermissionsWorkspace({ members, errorMessage }: { members: StaffPermission[]; errorMessage: string | null }) {
  const router = useRouter(); const [savingUserId, setSavingUserId] = useState<string | null>(null); const [message, setMessage] = useState("");
  async function save(member: StaffPermission, form: HTMLFormElement) { const data = new FormData(form); setSavingUserId(member.clerkUserId); setMessage(""); const result = await saveStaffSensitivePermissions({ clerkUserId: member.clerkUserId, propertyContacts: data.get("propertyContacts") === "on", unitAccess: data.get("unitAccess") === "on", consultationContacts: data.get("consultationContacts") === "on" }); setSavingUserId(null); setMessage(result.ok ? "직원 권한을 저장했습니다." : result.message); if (result.ok) router.refresh(); }
  return <section className="max-w-4xl rounded-xl border border-[#e5e1db] bg-white p-5"><h2 className="font-extrabold">직원별 민감정보 열람</h2><p className="mt-1 text-sm text-[#655f59]">admin은 항상 전체를 열람합니다. staff는 여기서 허용한 항목만 업무 화면에서 볼 수 있습니다. 다운로드 기능은 제공하지 않습니다.</p>{errorMessage && <p className="mt-4 rounded-lg border border-[#e7c3ba] bg-[#fff7f4] px-3 py-2 text-xs text-[#a84438]">{errorMessage}</p>}{message && <p className="mt-4 rounded-lg bg-[#f5eee9] px-3 py-2 text-xs text-[#655f59]">{message}</p>}<div className="mt-5 space-y-3">{members.map((member) => member.role === "admin" ? <div key={member.clerkUserId} className="rounded-lg bg-[#faf8f4] p-4"><p className="font-bold">관리자 계정</p><p className="mt-1 font-mono text-[11px] text-[#77736e]">{member.clerkUserId}</p><p className="mt-2 text-xs text-[#655f59]">관리자는 보안 관리 책임자로서 모든 제한 정보를 열람합니다.</p></div> : <form key={member.clerkUserId} className="rounded-lg border border-[#eeeae5] p-4" onSubmit={(event) => { event.preventDefault(); void save(member, event.currentTarget); }}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-bold">staff · {member.status === "active" ? "활성" : "비활성"}</p><p className="mt-1 font-mono text-[11px] text-[#77736e]">{member.clerkUserId}</p></div><button disabled={savingUserId === member.clerkUserId || member.status !== "active"} className="rounded-lg bg-[#3e3a37] px-3 py-2 text-xs font-bold text-white disabled:opacity-60">{savingUserId === member.clerkUserId ? "저장 중…" : "권한 저장"}</button></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{[["propertyContacts", "임대인·세입자 연락처", member.propertyContacts], ["unitAccess", "세대 비밀번호·출입 정보", member.unitAccess], ["consultationContacts", "상담 고객 연락처", member.consultationContacts]].map(([name, label, checked]) => <label className="flex items-start gap-2 rounded-md bg-[#faf8f4] p-3 text-xs font-bold text-[#655f59]" key={name as string}><input className="mt-0.5" defaultChecked={checked as boolean} disabled={member.status !== "active"} name={name as string} type="checkbox" /><span>{label}</span></label>)}</div></form>)}</div></section>;
}
