"use client";

import { connectConsultationInitialListing, type ConsultationListingOption } from "@/features/consultations/server/consultation-registration";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";

export function ConsultationInitialListingConnect({ consultationId, listingOptions }: { consultationId: string; listingOptions: ConsultationListingOption[] }) {
  const [open, setOpen] = useState(false); const [listingId, setListingId] = useState(""); const [query, setQuery] = useState(""); const [showResults, setShowResults] = useState(false); const [message, setMessage] = useState(""); const router = useRouter();
  const selected = listingOptions.find((listing) => listing.id === listingId);
  const results = useMemo(() => { const keyword = query.trim().toLocaleLowerCase("ko-KR"); return listingOptions.filter((listing) => !keyword || listing.label.toLocaleLowerCase("ko-KR").includes(keyword)).slice(0, 8); }, [listingOptions, query]);
  async function connect() { if (!listingId) { setMessage("연결할 매물을 선택해 주세요."); return; } const result = await connectConsultationInitialListing({ consultationId, listingId }); if (!result.ok) { setMessage(result.message); return; } setOpen(false); router.refresh(); }
  return <div className="mt-4">{!open ? <button className="rounded-lg bg-[#3e3a37] px-3 py-2 text-xs font-bold text-white" onClick={() => setOpen(true)} type="button">최초 문의 매물 연결</button> : <div className="space-y-2 rounded-lg bg-[#faf9f7] p-3"><div className="relative"><input className="field mt-0" onChange={(event) => { setQuery(event.target.value); setShowResults(true); }} onFocus={() => setShowResults(true)} placeholder="매물번호, 건물명, 호실로 검색" value={query} />{selected && <div className="mt-2 flex items-center justify-between gap-2 rounded-lg border border-[#d8d0c7] bg-white px-3 py-2 text-xs"><b>{selected.label}</b><button className="font-bold text-[#655f59] underline underline-offset-4" onClick={() => { setListingId(""); setQuery(""); }} type="button">선택 해제</button></div>}{showResults && <div className="absolute z-30 mt-1 max-h-56 w-full overflow-y-auto rounded-lg border border-[#ded7cf] bg-white p-1 shadow-lg">{results.length ? results.map((listing) => <button className="block w-full rounded-md px-3 py-2.5 text-left hover:bg-[#faf8f4]" key={listing.id} onClick={() => { setListingId(listing.id); setQuery(""); setShowResults(false); setMessage(""); }} type="button"><b className="text-xs">{listing.label}</b></button>) : <p className="px-3 py-4 text-xs text-[#7b7470]">일치하는 관리 중 매물이 없습니다.</p>}</div>}</div>{message && <p className="text-xs text-[#b94a42]">{message}</p>}<div className="flex justify-end gap-2"><button className="text-xs font-bold text-[#655f59]" onClick={() => setOpen(false)} type="button">취소</button><button className="rounded-lg bg-[#3e3a37] px-3 py-2 text-xs font-bold text-white" onClick={connect} type="button">매물 연결</button></div></div>}</div>;
}
