import { ContractActivityButton } from "@/features/contracts/components/contract-activity-button";
import { ContractDeleteButton } from "@/features/contracts/components/contract-delete-button";
import { ContractEditButton } from "@/features/contracts/components/contract-edit-button";
import { getContractDetail } from "@/features/contracts/server/contract-detail";
import { PageHeader } from "@/components/shared/page-header";
import Link from "next/link";

const statusLabels = { in_progress: "계약 진행", balance_due: "잔금 완료", completed: "계약 완료", cancelled: "취소", expired: "만료" };
const activityLabels = { provisional_contract: "가계약", formal_contract: "정식 계약", balance_due: "잔금 완료", completed: "계약 완료", cancelled: "해지", expired: "만료" };
const transactionLabels = { monthly_rent: "월세", jeonse: "전세", sale: "매매", to_be_confirmed: "확인 필요" };
const contractKindLabels = { new_contract: "신규 계약", renewal: "재계약" };

export default async function ContractDetailPage({ params }: { params: Promise<{ contractId: string }> }) {
  const { contractId } = await params;
  const { contract } = await getContractDetail(contractId);
  if (!contract) return <><PageHeader title="계약 상세" description="계약을 찾을 수 없습니다." /><Link href="/contracts" className="text-sm font-bold underline">계약 목록으로</Link></>;
  const initial = { transactionType: contract.transaction_type, contractKind: contract.contract_kind, brokerageType: contract.brokerage_type, contractStartedDate: contract.contract_started_date ?? "", officialContractDate: contract.official_contract_date ?? "", moveInDate: contract.move_in_date ?? "", endDate: contract.end_date ?? "", totalContractDepositAmount: contract.total_contract_deposit_amount?.toString() ?? "", provisionalDepositAmount: contract.provisional_deposit_amount?.toString() ?? "", additionalDepositDueDate: contract.additional_deposit_due_date ?? "", balanceAmount: contract.balance_amount?.toString() ?? "", balanceDueDate: contract.balance_due_date ?? "", note: contract.note ?? "" };
  return <><PageHeader title={`C-${String(contract.contract_reference_number).padStart(6, "0")}`} description="실제 계약 매물과 단계 이력을 확인합니다." action={<div className="flex gap-2"><ContractEditButton contractId={contract.id} initial={initial} /><ContractActivityButton contractId={contract.id} status={contract.status} /><ContractDeleteButton contractId={contract.id} status={contract.status} activityCount={contract.activities.length} /></div>} /><div className="mx-auto grid max-w-5xl gap-5 lg:grid-cols-2"><section className="rounded-xl border border-[#e5e1db] bg-white"><h2 className="border-b px-5 py-4 font-extrabold">계약 정보</h2><dl className="divide-y px-5 text-sm"><Row label="상태" value={statusLabels[contract.status as keyof typeof statusLabels]} /><Row label="실제 계약 매물" value={contract.listingLabel} /><Row label="출처 상담" value={contract.sourceLabel ?? "없음"} /><Row label="거래 방식" value={transactionLabels[contract.transaction_type as keyof typeof transactionLabels]} /><Row label="계약 구분" value={contractKindLabels[contract.contract_kind as keyof typeof contractKindLabels]} /><Row label="중개 방식" value={contract.brokerage_type === "co_brokerage" ? "공동 중개" : contract.brokerage_type === "other" ? "기타" : "단독 중개"} /></dl></section><section className="rounded-xl border border-[#e5e1db] bg-white"><h2 className="border-b px-5 py-4 font-extrabold">일정·금액</h2><dl className="divide-y px-5 text-sm"><Row label="정식 계약일" value={contract.official_contract_date ?? "—"} /><Row label="입주 / 만료" value={`${contract.move_in_date ?? "—"} / ${contract.end_date ?? "—"}`} /><Row label="전체 계약금 / 가계약금" value={`${money(contract.total_contract_deposit_amount)} / ${money(contract.provisional_deposit_amount)}`} /><Row label="잔금 / 예정일" value={`${money(contract.balance_amount)} / ${contract.balance_due_date ?? "—"}`} /></dl></section><section className="rounded-xl border border-[#e5e1db] bg-white lg:col-span-2"><h2 className="border-b px-5 py-4 font-extrabold">단계 이력</h2><div className="divide-y px-5">{contract.activities.map((item) => <div className="py-4" key={item.id}><b>{activityLabels[item.activity_type as keyof typeof activityLabels]}</b><span className="ml-2 font-mono text-xs text-[#77736e]">{item.activity_date}</span>{item.note && <p className="mt-1 text-sm text-[#655f59]">{item.note}</p>}</div>)}{contract.activities.length === 0 && <p className="py-8 text-sm text-[#77736e]">기록된 단계 이력이 없습니다.</p>}</div></section></div></>;
}

function Row({ label, value }: { label: string; value: string | undefined }) { return <div className="grid grid-cols-[9rem_1fr] gap-3 py-3"><dt className="font-bold text-[#77736e]">{label}</dt><dd>{value ?? "—"}</dd></div>; }
function money(value: number | null) { return value === null ? "—" : `${value.toLocaleString()}만원`; }
