"use client";

import { updateContractDetails } from "@/features/contracts/server/contract-registration";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Values = { transactionType: "monthly_rent" | "jeonse" | "sale" | "to_be_confirmed"; contractKind: "new_contract" | "renewal"; brokerageType: "direct" | "co_brokerage" | "other"; contractStartedDate: string; officialContractDate: string; moveInDate: string; endDate: string; totalContractDepositAmount: string; provisionalDepositAmount: string; additionalDepositDueDate: string; balanceAmount: string; balanceDueDate: string; note: string };

export function ContractEditButton({ contractId, initial }: { contractId: string; initial: Values }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [value, setValue] = useState(initial); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const change = (key: keyof Values, next: string) => setValue((current) => ({ ...current, [key]: next } as Values));
  async function save() { setSaving(true); setMessage(""); const result = await updateContractDetails(contractId, value); setSaving(false); if (!result.ok) { setMessage(result.message); return; } setOpen(false); router.refresh(); }
  return <><button type="button" onClick={() => setOpen(true)} className="rounded-lg border px-3 py-2 text-xs font-bold">계약 수정</button>{open && <div className="fixed inset-0 z-50 overflow-y-auto bg-[#2d2926]/35 p-4"><section className="mx-auto my-8 max-w-3xl rounded-xl bg-white p-5 shadow-xl"><h2 className="text-base font-extrabold">계약 정보 수정</h2><p className="mt-1 text-xs text-[#7b7470]">실제 계약 매물과 출처 상담은 이 화면에서 바꾸지 않습니다.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><Select label="거래 방식" value={value.transactionType} onChange={(next) => change("transactionType", next)} options={[["monthly_rent", "월세"], ["jeonse", "전세"], ["sale", "매매"], ["to_be_confirmed", "확인 필요"]]} /><Select label="계약 구분" value={value.contractKind} onChange={(next) => change("contractKind", next)} options={[["new_contract", "신규 계약"], ["renewal", "재계약"]]} /><Select label="중개 방식" value={value.brokerageType} onChange={(next) => change("brokerageType", next)} options={[["direct", "단독 중개"], ["co_brokerage", "공동 중개"], ["other", "기타"]]} /><Input label="계약 진행일" type="date" value={value.contractStartedDate} onChange={(next) => change("contractStartedDate", next)} /><Input label="정식 계약일" type="date" value={value.officialContractDate} onChange={(next) => change("officialContractDate", next)} /><Input label="입주일" type="date" value={value.moveInDate} onChange={(next) => change("moveInDate", next)} /><Input label="만료일" type="date" value={value.endDate} onChange={(next) => change("endDate", next)} /><Input label="전체 계약금 (만원)" value={value.totalContractDepositAmount} onChange={(next) => change("totalContractDepositAmount", next)} /><Input label="가계약금 (만원)" value={value.provisionalDepositAmount} onChange={(next) => change("provisionalDepositAmount", next)} /><Input label="추가 수령 예정일" type="date" value={value.additionalDepositDueDate} onChange={(next) => change("additionalDepositDueDate", next)} /><Input label="잔금 (만원)" value={value.balanceAmount} onChange={(next) => change("balanceAmount", next)} /><Input label="잔금 예정일" type="date" value={value.balanceDueDate} onChange={(next) => change("balanceDueDate", next)} /><label className="md:col-span-3"><span className="label">메모</span><textarea className="field min-h-20" value={value.note} onChange={(event) => change("note", event.target.value)} /></label></div>{message && <p className="mt-3 text-xs text-[#b94a42]">{message}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-lg border px-3 py-2 text-xs font-bold">취소</button><button type="button" disabled={saving} onClick={save} className="rounded-lg bg-[#3e3a37] px-3 py-2 text-xs font-bold text-white">{saving ? "저장 중…" : "저장"}</button></div></section></div>}</>;
}

function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string, string][] }) { return <label><span className="label">{label}</span><select className="field" value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function Input({ label, type = "text", value, onChange }: { label: string; type?: string; value: string; onChange: (value: string) => void }) { return <label><span className="label">{label}</span><input className="field" type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
