"use client";

import { buildings, listings } from "@/lib/mock-data/workspace";
import { useState } from "react";

export function BuildingExplorer() {
  const [buildingName, setBuildingName] = useState("대성빌");
  const building = buildings.find((item) => item.name === buildingName) ?? buildings[0];
  const [unit, setUnit] = useState("302호");
  const listing = listings.find((item) => item.building === building.name && item.unit === unit) ?? listings.find((item) => item.building === building.name);
  return <section className="grid gap-4 lg:grid-cols-[250px_250px_minmax(0,1fr)]"><div className="overflow-hidden rounded-xl border border-[#e5e1db] bg-white"><header className="border-b border-[#e5e1db] p-4 font-bold">건물 <span className="float-right font-mono text-[10px] text-[#77736e]">08 RESULTS</span></header>{buildings.map((item) => <button onClick={() => { setBuildingName(item.name); setUnit(item.units[0]); }} className={`w-full border-b border-[#eeeae5] px-4 py-3 text-left ${item.name === building.name ? "bg-[#f4f0e9]" : "hover:bg-[#faf8f4]"}`} key={item.name}><b className="text-xs">{item.name}</b><span className="mt-1 block text-[11px] text-[#77736e]">{item.address} · 호실 {item.units.length}개</span></button>)}</div><div className="overflow-hidden rounded-xl border border-[#e5e1db] bg-white"><header className="border-b border-[#e5e1db] p-4 font-bold">{building.name} 호실</header>{building.units.map((item) => { const itemListing = listings.find((row) => row.building === building.name && row.unit === item); return <button onClick={() => setUnit(item)} className={`w-full border-b border-[#eeeae5] px-4 py-3 text-left ${item === unit ? "bg-[#f4f0e9]" : "hover:bg-[#faf8f4]"}`} key={item}><b className="text-xs">{item}</b><span className="float-right text-[10px] font-bold text-[#657660]">{itemListing?.status ?? "종료"}</span><span className="mt-1 block text-[11px] text-[#77736e]">{itemListing?.layout ?? "과거 이력"}</span></button>; })}</div><article className="rounded-xl border border-[#e5e1db] bg-white p-5">{listing ? <><span className="rounded-full bg-[#eef2eb] px-2 py-1 text-[10px] font-bold text-[#657660]">현재 매물 · {listing.status}</span><h2 className="mt-3 text-xl font-extrabold">{listing.building} {listing.unit}</h2><p className="mt-1 text-xs text-[#77736e]">{listing.id} · {listing.layout}</p><p className="mt-6 font-mono text-lg font-bold text-[#3e3a37]">{listing.terms}</p><div className="mt-5 grid grid-cols-3 gap-2 text-[11px]"><div className="rounded-lg bg-[#faf9f7] p-3 text-[#77736e]">입주 가능<b className="mt-1 block text-[#292827]">{listing.available}</b></div><div className="rounded-lg bg-[#faf9f7] p-3 text-[#77736e]">확인 상태<b className="mt-1 block text-[#292827]">{listing.check}</b></div><div className="rounded-lg bg-[#faf9f7] p-3 text-[#77736e]">연결 상담<b className="mt-1 block text-[#292827]">1건</b></div></div><div className="mt-7 border-t border-[#e5e1db] pt-4"><h3 className="font-bold">매물 이력</h3><p className="mt-3 text-xs">현재 {listing.id}<span className="float-right text-[#77736e]">2026.08.18 ~</span></p><p className="mt-2 text-xs text-[#77736e]">종료 M-000019 <span className="float-right">2025.12.03 종료</span></p></div></> : <p>현재 매물이 없습니다.</p>}</article></section>;
}
