"use client";

import { StatusBadge } from "@/components/shared/status-badge";
import { buildingUpdateSchema, type BuildingUpdateInput, type UnitUpdateInput, unitUpdateSchema } from "@/features/listings/schemas/building-management";
import { updateManagedBuilding, updateManagedUnit, type BuildingManagementData, type ManagedBuilding, type ManagedUnit } from "@/features/listings/server/building-management";
import { zodResolver } from "@hookform/resolvers/zod";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";

const statusLabels = { vacant: "공실", contract_in_progress: "계약 진행", contract_complete: "계약 완료", on_hold: "보류", ended: "종료" } as const;
const propertyLabels: Record<string, string> = { one_room: "원룸", two_room: "투룸", two_bay: "투베이", three_room: "쓰리룸", owner_unit: "주인세대", apartment: "아파트", officetel: "오피스텔", retail: "상가", office: "사무실" };
const directionOptions = ["", "동향", "서향", "남향", "북향", "남동향", "남서향", "북동향", "북서향"];
const endReasonLabels = { other_broker_contract: "타 부동산 계약", other: "기타" } as const;

export function BuildingManagementWorkspace({ data }: { data: BuildingManagementData }) {
  const router = useRouter();
  const [buildingId, setBuildingId] = useState("");
  const building = data.buildings.find((item) => item.id === buildingId);
  const [unitId, setUnitId] = useState("");
  const unit = building?.units.find((item) => item.id === unitId);
  function selectBuilding(id: string) { setBuildingId(id); setUnitId(""); }
  if (data.context.kind !== "ready") return <Notice title={data.context.kind === "no-active-organization" ? "선택된 업무 조직이 없습니다" : "개발용 업무 조직 연결이 아직 없습니다"} description="선택한 Clerk 조직과 Dev DB의 활성 멤버 연결을 확인해 주세요." />;
  if (data.buildings.length === 0) return <Notice title="등록된 건물이 없습니다" description="먼저 신규 매물 등록에서 건물과 첫 호실을 함께 등록해 주세요." />;
  return <section className="grid gap-4 xl:grid-cols-[280px_260px_minmax(0,1fr)]"><BuildingList buildings={data.buildings} selectedId={building?.id ?? ""} onSelect={selectBuilding} /><UnitList building={building} selectedId={unit?.id ?? ""} onSelect={setUnitId} /><div className="space-y-4">{building ? <><BuildingEditor key={building.id} building={building} propertyContactsAllowed={data.sensitiveAccess.propertyContacts} onSaved={() => router.refresh()} /><UnitEditor key={unit?.id ?? "no-unit"} unit={unit} restrictedContactsAvailable={data.restrictedContactsAvailable} propertyContactsAllowed={data.sensitiveAccess.propertyContacts} unitAccessAllowed={data.sensitiveAccess.unitAccess} onSaved={() => router.refresh()} /></> : <Notice title="건물을 선택해 주세요" description="왼쪽에서 지역을 고르거나 건물명·주소를 검색한 뒤, 관리할 건물을 선택하세요." />}</div></section>;
}

function BuildingList({ buildings, selectedId, onSelect }: { buildings: ManagedBuilding[]; selectedId: string; onSelect: (id: string) => void }) {
  const [query, setQuery] = useState("");
  const [recentIds, setRecentIds] = useState<string[]>([]);
  const [area, setArea] = useState("");
  useEffect(() => { const frame = window.requestAnimationFrame(() => { try { const saved = JSON.parse(window.localStorage.getItem("realestate-recent-building-ids") ?? "[]"); if (Array.isArray(saved)) setRecentIds(saved.filter((id): id is string => typeof id === "string")); } catch { setRecentIds([]); } }); return () => window.cancelAnimationFrame(frame); }, []);
  const normalizedQuery = query.trim().toLowerCase();
  const areaCounts = new Map<string, number>();
  buildings.forEach((item) => { const key = areaName(item); areaCounts.set(key, (areaCounts.get(key) ?? 0) + 1); });
  const areas = [...areaCounts.entries()].sort(([left], [right]) => left.localeCompare(right, "ko"));
  const matched = normalizedQuery ? buildings.filter((item) => `${item.name} ${item.roadAddress ?? ""} ${item.lotAddress ?? ""} ${item.addressDetail ?? ""}`.toLowerCase().includes(normalizedQuery)) : area ? buildings.filter((item) => areaName(item) === area) : recentIds.map((id) => buildings.find((item) => item.id === id)).filter((item): item is ManagedBuilding => Boolean(item));
  function select(id: string) { const next = [id, ...recentIds.filter((item) => item !== id)].slice(0, 8); setRecentIds(next); window.localStorage.setItem("realestate-recent-building-ids", JSON.stringify(next)); onSelect(id); }
  const heading = normalizedQuery ? `검색 결과 ${matched.length}곳` : area ? `${area} 건물 ${matched.length}곳` : "최근 본 건물";
  return <section className="overflow-hidden rounded-xl border border-[#e5e1db] bg-white"><header className="border-b border-[#e5e1db] px-4 py-4"><div className="flex items-center justify-between"><b>건물</b><span className="font-mono text-[10px] text-[#77736e]">전체 {buildings.length}곳</span></div><input aria-label="건물명 또는 주소 검색" className="field mt-3" onChange={(event) => { setQuery(event.target.value); if (event.target.value) setArea(""); }} placeholder="건물명·주소 검색" value={query} /><div className="mt-3 flex flex-wrap gap-1.5">{areas.map(([name, count]) => <button className={`rounded-full border px-2.5 py-1 text-[10px] font-bold ${area === name ? "border-[#3e3a37] bg-[#3e3a37] text-white" : "border-[#ded7d0] text-[#655f59]"}`} key={name} onClick={() => { setArea((current) => current === name ? "" : name); setQuery(""); }} type="button">{name} {count}</button>)}</div></header><div className="border-b border-[#eeeae5] px-4 py-2 text-[11px] font-bold text-[#77736e]">{heading}</div><div className="max-h-[650px] overflow-y-auto">{matched.map((item) => <button className={`w-full border-b border-[#eeeae5] px-4 py-3 text-left ${item.id === selectedId ? "bg-[#f4f0e9]" : "hover:bg-[#faf8f4]"}`} key={item.id} onClick={() => select(item.id)} type="button"><div className="flex items-center justify-between gap-2"><b className="text-sm">{item.name}</b><span className="text-[10px] font-bold text-[#8b8279]">공실 {vacantCount(item)} · 호실 {item.units.length}</span></div><span className="mt-1 block text-[11px] text-[#77736e]">{item.roadAddress ?? item.lotAddress ?? "주소 미입력"}</span></button>)}{matched.length === 0 && <p className="px-4 py-10 text-center text-xs text-[#7b7470]">{normalizedQuery ? "일치하는 건물이 없습니다." : area ? "이 지역에 등록된 건물이 없습니다." : "지역을 선택하거나 건물명·주소를 검색해 보세요. 선택한 건물은 여기에 다시 표시됩니다."}</p>}</div></section>;
}

function areaName(building: ManagedBuilding) { const source = building.lotAddress ?? building.roadAddress ?? ""; return source.match(/([가-힣]+(?:동|읍|면|리))/)?.[1] ?? "기타"; }
function vacantCount(building: ManagedBuilding) { return building.units.filter((unit) => unit.history.some((item) => item.isCurrent && item.status === "vacant")).length; }

function UnitList({ building, selectedId, onSelect }: { building?: ManagedBuilding; selectedId: string; onSelect: (id: string) => void }) {
  if (!building) return <Notice title="건물을 먼저 선택해 주세요" description="선택한 건물의 호실과 현재 매물 이력이 여기에 표시됩니다." />;
  return <section className="overflow-hidden rounded-xl border border-[#e5e1db] bg-white"><header className="border-b border-[#e5e1db] px-4 py-4"><b>{building.name} 호실</b><span className="float-right font-mono text-[10px] text-[#77736e]">{building.units.length}개</span></header><div className="max-h-[650px] overflow-y-auto">{building.units.map((item) => { const current = item.history.find((history) => history.isCurrent); return <button className={`w-full border-b border-[#eeeae5] px-4 py-3 text-left ${item.id === selectedId ? "bg-[#f4f0e9]" : "hover:bg-[#faf8f4]"}`} key={item.id} onClick={() => onSelect(item.id)} type="button"><div className="flex items-center justify-between gap-2"><b className="text-sm">{item.unitNumber}</b>{current ? <StatusBadge tone={current.status === "vacant" ? "active" : current.status === "contract_in_progress" ? "notice" : "neutral"}>{statusLabels[current.status]}</StatusBadge> : <StatusBadge>현재 매물 없음</StatusBadge>}</div><span className="mt-1 block text-[11px] text-[#77736e]">{item.floor === null ? "층 미입력" : `${item.floor}층`}{item.direction ? ` · ${item.direction}` : ""}</span></button>; })}{building.units.length === 0 && <p className="px-4 py-8 text-center text-xs text-[#7b7470]">등록된 호실이 없습니다.</p>}</div></section>;
}

function BuildingEditor({ building, propertyContactsAllowed, onSaved }: { building: ManagedBuilding; propertyContactsAllowed: boolean; onSaved: () => void }) {
  const form = useForm<BuildingUpdateInput>({ resolver: zodResolver(buildingUpdateSchema), defaultValues: valuesForBuilding(building) });
  useEffect(() => form.reset(valuesForBuilding(building)), [building, form]);
  async function submit(values: BuildingUpdateInput) { const result = await updateManagedBuilding(values); if (!result.ok) { setErrors(form, result); return; } onSaved(); }
  return <form className="rounded-xl border border-[#e5e1db] bg-white" onSubmit={form.handleSubmit(submit)}><SectionHeader title="건물 공통 정보" description="주소와 임대인 연락처는 같은 건물의 호실이 함께 사용합니다." /><div className="grid gap-4 p-5 md:grid-cols-2"><Field label="건물명" error={form.formState.errors.name?.message}><input className="field" {...form.register("name")} /></Field><Field label="도로명 주소" error={form.formState.errors.roadAddress?.message}><input className="field" {...form.register("roadAddress")} /></Field><Field label="지번 주소"><input className="field" {...form.register("lotAddress")} /></Field><Field label="상세 주소"><input className="field" {...form.register("addressDetail")} /></Field><Field label="우편번호"><input className="field" {...form.register("postalCode")} /></Field>{propertyContactsAllowed && <Field label="임대인 연락처 (제한 정보)" error={form.formState.errors.ownerPhone?.message}><input className="field" inputMode="tel" type="tel" {...form.register("ownerPhone")} /></Field>}</div><SaveBar saving={form.formState.isSubmitting} message={form.formState.errors.root?.message} label="건물 정보 저장" /></form>;
}

function UnitEditor({ unit, restrictedContactsAvailable, propertyContactsAllowed, unitAccessAllowed, onSaved }: { unit?: ManagedUnit; restrictedContactsAvailable: boolean; propertyContactsAllowed: boolean; unitAccessAllowed: boolean; onSaved: () => void }) {
  const form = useForm<UnitUpdateInput>({ resolver: zodResolver(unitUpdateSchema), defaultValues: unit ? valuesForUnit(unit) : undefined });
  useEffect(() => { if (unit) form.reset(valuesForUnit(unit)); }, [unit, form]);
  if (!unit) return <section className="rounded-xl border border-[#e5e1db] bg-white px-6 py-10 text-center text-sm text-[#7b7470]">왼쪽에서 호실을 선택해 주세요.</section>;
  async function submit(values: UnitUpdateInput) { const result = await updateManagedUnit(values); if (!result.ok) { setErrors(form, result); return; } onSaved(); }
  const current = unit.history.find((item) => item.isCurrent); const history = unit.history.filter((item) => !item.isCurrent);
  return <form className="rounded-xl border border-[#e5e1db] bg-white" onSubmit={form.handleSubmit(submit)}><SectionHeader title={`${unit.unitNumber} 고정 정보`} description="층·방향·옵션은 호실에 저장됩니다. 가격과 공실 상태는 현재 매물에서 수정합니다." /><div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3"><Field label="호실" error={form.formState.errors.unitNumber?.message}><input className="field" {...form.register("unitNumber")} /></Field><Field label="층" error={form.formState.errors.floor?.message}><input className="field" inputMode="numeric" {...form.register("floor")} /></Field><Field label="방향"><select className="field" {...form.register("direction")}>{directionOptions.map((value) => <option key={value} value={value}>{value || "선택 안 함"}</option>)}</select></Field><label className="md:col-span-2 xl:col-span-3"><span className="label">고정 옵션</span><input className="field" placeholder="예: 엘리베이터, 주차, 에어컨" {...form.register("optionsText")} /></label>{unitAccessAllowed && <Field label="세대 비밀번호 (제한 정보)"><input autoComplete="new-password" className="field" type="password" {...form.register("accessPassword")} /></Field>}{propertyContactsAllowed && <Field label="세입자 연락처 (제한 정보)" error={form.formState.errors.tenantPhone?.message}><input className="field" inputMode="tel" type="tel" {...form.register("tenantPhone")} />{!restrictedContactsAvailable && <span className="mt-1 block text-[11px] text-[#a85f43]">세입자 연락처 기능을 쓰려면 20260826000700 migration을 Dev DB에 적용해야 합니다.</span>}</Field>}</div><ListingHistory current={current} history={history} /><SaveBar saving={form.formState.isSubmitting} message={form.formState.errors.root?.message} label="호실 정보 저장" /></form>;
}

function ListingHistory({ current, history }: { current?: ManagedUnit["history"][number]; history: ManagedUnit["history"] }) { return <div className="border-t border-[#eeeae5] px-5 py-4"><div className="flex items-center justify-between"><h3 className="text-sm font-extrabold">매물 이력</h3><span className="text-[11px] text-[#7b7470]">현재 1건 · 과거 {history.length}건</span></div>{current ? <HistoryRow item={current} title="현재 매물" /> : <p className="mt-3 text-xs text-[#7b7470]">현재 매물이 없습니다.</p>}{history.length > 0 && <div className="mt-2 border-t border-dashed border-[#e5e1db] pt-2">{history.map((item) => <HistoryRow item={item} key={item.id} title="과거 매물" />)}</div>}</div>; }
function HistoryRow({ item, title }: { item: ManagedUnit["history"][number]; title: string }) { return <div className="mt-2 flex items-center justify-between gap-3 rounded-lg bg-[#faf9f7] px-3 py-2 text-xs"><span><b>{title}</b> <span className="ml-1 font-mono text-[#77736e]">M-{String(item.referenceNumber).padStart(6, "0")}</span> · {propertyLabels[item.propertyType] ?? item.propertyType}{item.endReason ? ` · ${endReasonLabels[item.endReason]}` : ""}</span><div className="flex items-center gap-2"><StatusBadge tone={item.status === "vacant" ? "active" : item.status === "contract_in_progress" ? "notice" : "neutral"}>{statusLabels[item.status]}</StatusBadge><Link className="font-bold underline underline-offset-4" href={item.isCurrent ? `/listings/${item.id}` : `/listings/${item.id}/history`}>{item.isCurrent ? "현재 매물 열기" : "이력 열기"}</Link></div></div>; }
function valuesForBuilding(building: ManagedBuilding): BuildingUpdateInput { return { id: building.id, name: building.name, roadAddress: building.roadAddress ?? "", lotAddress: building.lotAddress ?? "", addressDetail: building.addressDetail ?? "", postalCode: building.postalCode ?? "", ownerPhone: building.ownerPhone }; }
function valuesForUnit(unit: ManagedUnit): UnitUpdateInput { return { id: unit.id, buildingId: unit.buildingId, unitNumber: unit.unitNumber, floor: unit.floor?.toString() ?? "", direction: unit.direction ?? "", optionsText: unit.options.join(", "), accessPassword: unit.accessPassword, tenantPhone: unit.tenantPhone }; }
function setErrors<T extends Record<string, unknown>>(form: ReturnType<typeof useForm<T>>, result: { message: string; fieldErrors?: Record<string, string[]> }) { Object.entries(result.fieldErrors ?? {}).forEach(([name, messages]) => form.setError(name as never, { message: messages[0] })); form.setError("root", { message: result.message }); }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label><span className="label">{label}</span>{children}{error && <span className="mt-1 block text-xs text-[#b94a42]">{error}</span>}</label>; }
function SectionHeader({ title, description }: { title: string; description: string }) { return <div className="border-b border-[#e5e1db] px-5 py-4"><h2 className="text-base font-extrabold">{title}</h2><p className="mt-1 text-xs text-[#7b7470]">{description}</p></div>; }
function SaveBar({ saving, message, label }: { saving: boolean; message?: string; label: string }) { return <div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#eeeae5] px-5 py-4">{message ? <p role="alert" className="text-xs text-[#b94a42]">{message}</p> : <span className="text-xs text-[#7b7470]">저장하면 같은 조직의 해당 정보만 갱신됩니다.</span>}<button className="rounded-lg bg-[#3e3a37] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-60" disabled={saving} type="submit">{saving ? "저장 중…" : label}</button></div>; }
function Notice({ title, description }: { title: string; description: string }) { return <section className="rounded-xl border border-[#e8e1db] bg-white px-6 py-14 text-center"><h2 className="text-base font-extrabold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm text-[#7b7470]">{description}</p></section>; }
