"use client";

import { RotateCcw, Search, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { quickFilters } from "./listing-data";

export function ListingFilterPanel() {
  const [selected, setSelected] = useState<(typeof quickFilters)[number]>(quickFilters[0]);
  return <section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm shadow-slate-200/40 sm:p-6"><div className="flex flex-wrap items-center gap-2 border-b border-slate-100 pb-4"><span className="mr-1 text-xs font-bold uppercase tracking-wider text-slate-400">추천 필터</span>{quickFilters.map((filter) => <button key={filter} type="button" onClick={() => setSelected(filter)} className={`rounded-xl px-3 py-2 text-xs font-semibold transition-colors ${selected === filter ? "bg-blue-600 text-white shadow-sm shadow-blue-600/20" : "bg-slate-50 text-slate-600 ring-1 ring-slate-200 hover:bg-slate-100"}`}>{filter}</button>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-semibold text-slate-500">통합 검색</span><span className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none transition focus:border-blue-400 focus:ring-4 focus:ring-blue-100" placeholder="건물명, 호실, 주소로 검색" /></span></label><label><span className="mb-1.5 block text-xs font-semibold text-slate-500">매물 상태</span><select className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-600 outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-100"><option>전체 상태</option><option>공실</option><option>입주예정</option><option>계약진행</option></select></label><label><span className="mb-1.5 block text-xs font-semibold text-slate-500">거래 방식</span><select className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-600 outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-100"><option>월세 · 전세 전체</option><option>월세</option><option>전세</option></select></label></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><p className="text-xs text-slate-400">가공 데이터 미리보기 · 실제 검색은 DB 연결 후 작동합니다.</p><div className="flex gap-2"><button type="button" className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-xs font-semibold text-slate-500 hover:bg-slate-100"><RotateCcw className="size-3.5" /> 초기화</button><button type="button" className="inline-flex items-center gap-1.5 rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white"><SlidersHorizontal className="size-3.5" /> 상세 필터</button></div></div></section>;
}
