"use client";

import { defaultAdvertisingCopyTemplates } from "@/features/advertisements/default-copy-templates";
import { hasSensitiveCopy, propertyGroupLabels, propertyGroups, type PropertyGroup } from "@/features/advertisements/schemas/advertising-copy-template";
import { useState } from "react";

const emptyValues = { 주소: "", 매물유형: "", 거래조건: "", 관리비: "", 입주가능일: "", 특징: "" };

function render(template: string, values: Record<string, string>) { return template.replace(/\{\{([^{}]+)\}\}/g, (_, key: string) => values[key.trim()] || ""); }

export function AdvertisingCopyWorkspace() {
  const [group, setGroup] = useState<PropertyGroup>("residential"); const [selectedTemplateId, setSelectedTemplateId] = useState(""); const [values, setValues] = useState<Record<string, string>>(emptyValues); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [copyMessage, setCopyMessage] = useState("");
  const activeTemplates = defaultAdvertisingCopyTemplates.filter((item) => item.propertyGroup === group); const selectedTemplate = activeTemplates.find((item) => item.id === selectedTemplateId) ?? activeTemplates[0] ?? null;
  function makeCopy() { if (!selectedTemplate) { setCopyMessage("먼저 사용할 템플릿을 선택해 주세요."); return; } if (Object.values(values).some(hasSensitiveCopy)) { setCopyMessage("입력값에 연락처·비밀번호·내부 메모처럼 민감한 정보가 있습니다. 지운 뒤 다시 만들어 주세요."); return; } const next = { ...values, 매물유형: values.매물유형 || propertyGroupLabels[group] }; setTitle(render(selectedTemplate.titleTemplate, next).trim()); setBody(render(selectedTemplate.bodyTemplate, next).trim()); setCopyMessage("문구를 만들었습니다. 결과를 필요한 만큼 수정한 뒤 복사하세요."); }
  async function copy(text: string, label: string) { if (!text.trim()) { setCopyMessage("먼저 문구를 만들어 주세요."); return; } if (hasSensitiveCopy(text)) { setCopyMessage("결과에 민감한 정보가 있어 복사할 수 없습니다. 해당 내용을 지워 주세요."); return; } try { await navigator.clipboard.writeText(text); setCopyMessage(`${label}을 복사했습니다.`); } catch { setCopyMessage("자동 복사가 되지 않았습니다. 문구를 직접 선택해 복사해 주세요."); } }
  return <section className="space-y-5 rounded-xl border border-[#e5e1db] bg-white p-5"><div><h2 className="font-extrabold">매물 유형별 광고 문구</h2><p className="mt-1 text-xs text-[#77736e]">기본 템플릿에 확인한 값만 넣어 복사합니다. 결과 문구는 저장되지 않고 매물 상태도 바꾸지 않습니다.</p></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)]"><div className="space-y-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{propertyGroups.map((item) => <button type="button" key={item} onClick={() => { setGroup(item); setSelectedTemplateId(""); setTitle(""); setBody(""); }} className={`rounded-lg border px-3 py-2 text-xs font-bold ${group === item ? "border-[#a85f43] bg-[#f7ebe5] text-[#a84438]" : "border-[#e5e1db] text-[#655f59]"}`}>{propertyGroupLabels[item]}</button>)}</div><div className="rounded-lg bg-[#faf8f4] p-4"><p className="text-xs font-bold text-[#655f59]">사용할 템플릿</p><p className="mt-1 text-[11px] text-[#77736e]">기본 템플릿은 Streamlit의 기본형·특징 강조형 흐름을 정리한 읽기 전용 문구입니다.</p><select className="field mt-3" value={selectedTemplate?.id ?? ""} onChange={(event) => setSelectedTemplateId(event.target.value)}>{activeTemplates.map((item) => <option key={item.id} value={item.id}>{defaultAdvertisingCopyTemplates.some((defaultItem) => defaultItem.id === item.id) ? `[기본] ${item.templateName}` : item.templateName}</option>)}</select></div><div className="grid gap-3 sm:grid-cols-2">{(["주소", "매물유형", "거래조건", "관리비", "입주가능일", "특징"] as const).map((key) => <label key={key} className={key === "특징" ? "sm:col-span-2" : ""}><span className="label">{key} {key === "매물유형" ? "(비우면 선택 유형 사용)" : ""}</span>{key === "특징" ? <textarea className="field min-h-20 py-2" placeholder="확인한 장점만 입력" value={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.value })} /> : <input className="field" placeholder="확인한 값만 입력" value={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.value })} />}</label>)}</div><button type="button" onClick={makeCopy} className="w-full rounded-lg bg-[#3e3a37] px-4 py-3 text-sm font-bold text-white">문구 만들기</button></div>
      <div className="rounded-lg border border-[#eeeae5] p-4"><h3 className="font-extrabold">복사 전 결과 확인</h3><p className="mt-1 text-xs text-[#77736e]">연락처, 비밀번호, 출입·내부 메모는 결과에 넣을 수 없습니다.</p><label className="mt-4 block"><span className="label">제목</span><textarea className="field min-h-18 py-2" value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="mt-4 block"><span className="label">본문</span><textarea className="field min-h-52 py-2" value={body} onChange={(event) => setBody(event.target.value)} /></label><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => copy(title, "제목")} className="rounded-md border border-[#d8d0c7] px-3 py-2 text-xs font-bold text-[#655f59]">제목 복사</button><button type="button" onClick={() => copy(body, "본문")} className="rounded-md border border-[#d8d0c7] px-3 py-2 text-xs font-bold text-[#655f59]">본문 복사</button><button type="button" onClick={() => copy(`${title}\n${body}`.trim(), "제목과 본문")} className="rounded-md border border-[#3e3a37] px-3 py-2 text-xs font-bold text-[#3e3a37]">전체 복사</button></div>{copyMessage && <p className="mt-3 text-xs text-[#655f59]">{copyMessage}</p>}</div></div>
  </section>;
}
