"use client";

import { deleteMonthlyAdvertisingCost, saveMonthlyAdvertisingCost, type AdvertisingCostItem } from "@/features/advertisements/server/advertising-costs";
import { advertisingCostSchema, advertisingPlatforms, type AdvertisingCostInput } from "@/features/advertisements/schemas/advertising-cost";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { useMemo, useState } from "react";

const currentMonth = new Date().toISOString().slice(0, 7);
const defaultValues: AdvertisingCostInput = { billingMonth: currentMonth, platformPreset: "당근", customPlatform: "", amount: "", memo: "" };
const formatWon = (amount: number) => `${new Intl.NumberFormat("ko-KR").format(amount)}원`;
const isPreset = (platform: string): platform is Exclude<(typeof advertisingPlatforms)[number], "기타"> => platform !== "기타" && (advertisingPlatforms as readonly string[]).includes(platform);

export function AdvertisingCostWorkspace({ billingMonth, costs, loadError }: { billingMonth: string; costs: AdvertisingCostItem[]; loadError: string | null }) {
  const router = useRouter();
  const form = useForm<AdvertisingCostInput>({ resolver: zodResolver(advertisingCostSchema), defaultValues: { ...defaultValues, billingMonth } });
  const [saving, setSaving] = useState(false); const [deletingId, setDeletingId] = useState<string | null>(null); const [message, setMessage] = useState(""); const [selectedPreset, setSelectedPreset] = useState<AdvertisingCostInput["platformPreset"]>("당근");
  const platformPresetField = form.register("platformPreset"); const total = useMemo(() => costs.reduce((sum, item) => sum + item.amount, 0), [costs]);
  function selectMonth(nextMonth: string) { if (nextMonth) router.replace(`/advertisements?month=${nextMonth}`); }
  function edit(item: AdvertisingCostItem) { const platformPreset = isPreset(item.platform) ? item.platform : "기타"; setSelectedPreset(platformPreset); form.reset({ billingMonth, platformPreset, customPlatform: isPreset(item.platform) ? "" : item.platform, amount: String(item.amount), memo: item.memo ?? "" }); setMessage(`“${item.platform}” 금액을 수정합니다. 저장하면 같은 월의 기존 기록이 바뀝니다.`); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit(values: AdvertisingCostInput) { setSaving(true); setMessage(""); const result = await saveMonthlyAdvertisingCost(values); setSaving(false); if (!result.ok) { form.setError("root", { message: result.message }); return; } setSelectedPreset("당근"); form.reset({ ...defaultValues, billingMonth: values.billingMonth }); setMessage(result.mode === "updated" ? "기존 광고비를 수정했습니다." : "월별 광고비를 저장했습니다."); router.refresh(); }
  async function remove(item: AdvertisingCostItem) { if (!window.confirm(`${billingMonth} ${item.platform} 광고비 ${formatWon(item.amount)}을 삭제할까요? 이 기록만 삭제되며 다른 업무 정보는 바뀌지 않습니다.`)) return; setDeletingId(item.id); setMessage(""); const result = await deleteMonthlyAdvertisingCost(item.id); setDeletingId(null); if (!result.ok) { setMessage(result.message); return; } setMessage("광고비 기록을 삭제했습니다."); router.refresh(); }
  return <div className="max-w-5xl space-y-5">
    <section className="rounded-xl border border-[#e5e1db] bg-white p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-extrabold">월별 플랫폼 광고비</h2><p className="mt-1 text-xs text-[#77736e]">플랫폼별 한 달 총액만 기록합니다. 매물·상담·계약에는 자동으로 연결되지 않습니다.</p></div><label className="w-full sm:w-44"><span className="label">조회 기준월</span><input className="field" type="month" value={billingMonth} onChange={(event) => selectMonth(event.target.value)} /></label></div>{loadError && <p className="mt-4 rounded-lg border border-[#e7c3ba] bg-[#fff7f4] px-3 py-2 text-xs text-[#a84438]">{loadError}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-lg bg-[#faf8f4] p-4"><p className="text-xs font-bold text-[#77736e]">{billingMonth} 전체</p><p className="mt-2 text-xl font-extrabold">{formatWon(total)}</p></div>{costs.map((item) => <div key={item.id} className="rounded-lg border border-[#eeeae5] p-4"><p className="text-xs font-bold text-[#77736e]">{item.platform}</p><p className="mt-2 text-lg font-extrabold">{formatWon(item.amount)}</p></div>)}</div></section>
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.25fr)]">
      <form className="rounded-xl border border-[#e5e1db] bg-white p-5" onSubmit={form.handleSubmit(submit)}><div><h2 className="font-extrabold">광고비 입력</h2><p className="mt-1 text-xs text-[#77736e]">같은 기준월과 플랫폼을 다시 저장하면 새 기록이 아닌 수정으로 처리합니다.</p></div><div className="mt-5 space-y-4"><label><span className="label">기준월</span><input className="field" type="month" {...form.register("billingMonth")} /></label><label><span className="label">플랫폼</span><select className="field" {...platformPresetField} onChange={(event) => { platformPresetField.onChange(event); setSelectedPreset(event.target.value as AdvertisingCostInput["platformPreset"]); }}>{advertisingPlatforms.map((platform) => <option key={platform} value={platform}>{platform}</option>)}</select></label>{selectedPreset === "기타" && <label><span className="label">기타 플랫폼명</span><input className="field" placeholder="예: 지역 커뮤니티" {...form.register("customPlatform")} /></label>}<label><span className="label">월 총 광고비</span><input className="field" inputMode="numeric" placeholder="예: 120000" {...form.register("amount")} /><span className="mt-1 block text-[11px] text-[#8a837c]">원 단위의 숫자만 입력합니다.</span></label><label><span className="label">메모 (선택)</span><textarea className="field min-h-24 py-2" placeholder="예: 8월 상단 노출 상품" {...form.register("memo")} /></label></div>{form.formState.errors.root?.message && <p className="mt-3 text-xs text-[#b94a42]">{form.formState.errors.root.message}</p>}{form.formState.errors.customPlatform?.message && <p className="mt-3 text-xs text-[#b94a42]">{form.formState.errors.customPlatform.message}</p>}<button disabled={saving} className="mt-5 w-full rounded-lg bg-[#3e3a37] px-4 py-3 text-sm font-bold text-white">{saving ? "저장 중…" : "광고비 저장"}</button></form>
      <section className="rounded-xl border border-[#e5e1db] bg-white p-5"><div><h2 className="font-extrabold">{billingMonth} 기록</h2><p className="mt-1 text-xs text-[#77736e]">총 {costs.length}개 플랫폼 · 합계 {formatWon(total)}</p></div>{message && <p className="mt-4 rounded-lg bg-[#f5eee9] px-3 py-2 text-xs text-[#655f59]">{message}</p>}{costs.length === 0 ? <div className="mt-8 rounded-lg border border-dashed border-[#ddd5cd] px-4 py-10 text-center text-sm text-[#7b7470]">이 달에 저장된 광고비가 없습니다.</div> : <ul className="mt-4 divide-y divide-[#eeeae5]">{costs.map((item) => <li key={item.id} className="py-4"><div className="flex items-start justify-between gap-4"><div><p className="font-bold">{item.platform} <span className="ml-2 font-mono text-sm">{formatWon(item.amount)}</span></p>{item.memo && <p className="mt-1 whitespace-pre-wrap text-xs text-[#77736e]">{item.memo}</p>}</div><div className="flex shrink-0 gap-2"><button type="button" onClick={() => edit(item)} className="rounded-md border border-[#d8d0c7] px-2.5 py-1.5 text-xs font-bold text-[#655f59]">수정</button><button type="button" disabled={deletingId === item.id} onClick={() => remove(item)} className="rounded-md border border-[#dfb4aa] px-2.5 py-1.5 text-xs font-bold text-[#a84438]">{deletingId === item.id ? "삭제 중…" : "삭제"}</button></div></div></li>)}</ul>}</section>
    </div>
    <section className="rounded-xl border border-[#e5e1db] bg-[#fdfaf8] p-5"><h2 className="font-extrabold">광고비 사용 범위</h2><p className="mt-1 text-sm text-[#655f59]">현재 광고비는 플랫폼별 월 총액만 저장하며, 광고 성과를 자동 계산하거나 외부 광고 사이트와 연결하지 않습니다.</p></section>
  </div>;
}
