import { StatusBadge } from "@/components/shared/status-badge";
import { propertyGroups, propertyPreviews, type PropertyGroup } from "@/features/property-types/mock-data";
import Link from "next/link";

export function PropertyTypePreviewWorkspace({ selected, basePath = "/property-types" }: { selected: string; basePath?: string }) {
  const selectedGroup = propertyGroups.find((item) => item.id === selected)?.id ?? "all";
  const rows = selectedGroup === "all" ? propertyPreviews : propertyPreviews.filter((item) => item.group === selectedGroup as PropertyGroup);
  return <><FlowGuide active="목록" /><section className="rounded-xl border border-[#e5e1db] bg-white"><div className="flex flex-wrap gap-2 border-b border-[#e5e1db] p-4">{propertyGroups.map((group) => <Link className={`rounded-full border px-3 py-1.5 text-xs font-bold ${group.id === selectedGroup ? "border-[#3e3a37] bg-[#3e3a37] text-white" : "border-[#ded7d0] text-[#655f59]"}`} href={group.id === "all" ? basePath : `${basePath}?type=${group.id}`} key={group.id}>{group.label}</Link>)}</div><div className="divide-y divide-[#eeeae5]">{rows.map((item) => <Link className="block px-5 py-4 hover:bg-[#faf8f4]" href={`${basePath}/${item.id}`} key={item.id}><div className="flex flex-wrap items-center gap-2"><StatusBadge tone={item.status === "공실" ? "active" : item.status === "계약 진행" ? "notice" : "neutral"}>{item.status}</StatusBadge><span className="rounded bg-[#f2eee9] px-1.5 py-0.5 text-[10px] font-bold text-[#655f59]">{item.typeLabel}</span><span className="font-mono text-[11px] text-[#8b8279]">{item.referenceNumber}</span></div><div className="mt-2 flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><div><b>{item.buildingName} {item.unitLabel}</b><p className="mt-1 text-xs text-[#77736e]">{item.address} · {item.availability}</p></div><b className="font-mono text-sm">{item.price}</b></div></Link>)}</div></section></>;
}

export function FlowGuide({ active }: { active: "목록" | "상세" | "등록" }) { const steps = ["유형 선택", "목록", "상세", "유형별 등록", "상담·계약 공통 관리"]; return <div className="mb-5 rounded-xl border border-[#e8e1db] bg-[#fffdf9] px-4 py-3"><p className="text-xs font-bold text-[#655f59]">확장 업무 흐름 미리보기</p><div className="mt-2 flex flex-wrap items-center gap-2 text-[11px]">{steps.map((step, index) => <span className={step === active ? "font-bold text-[#8f4e36]" : "text-[#7b7470]"} key={step}>{index > 0 && <span className="mr-2 text-[#b7aea7]">→</span>}{step}</span>)}</div></div>; }
