"use server";

import { revenueEntrySchema, revenueSettlementSchema, type RevenueEntryInput, type RevenueSettlementInput } from "@/features/revenue/schemas/revenue";
import { getOrganizationContext } from "@/lib/auth/organization-context";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";

type Result = { ok: true } | { ok: false; message: string; fieldErrors?: Record<string, string[]> };
export type RevenueEntry = { id: string; entryType: "receipt" | "refund"; entryDate: string; grossAmount: number; externalAmount: number; officeAmount: number; staffAmount: number; officeRate: number; staffRate: number; memo: string | null };
export type RevenueDetail = { canManage: boolean; responsible: string | null; defaultOfficeRate: number; defaultStaffRate: number; settlement: { tenantCommissionAmount: number; landlordCommissionAmount: number; agreed: number; officeRate: number; staffRate: number; note: string | null } | null; entries: RevenueEntry[]; received: number; refunded: number; outstanding: number; officeNet: number; staffNet: number };

export async function getResponsibleMemberOptions() { const context = await getOrganizationContext(); if (context.kind !== "ready") return { context, members: [] as string[] }; const supabase = createSupabaseServerClient(); const { data } = await supabase.from("organization_members").select("clerk_user_id").eq("organization_id", context.organizationId).eq("status", "active").order("clerk_user_id"); return { context, members: (data ?? []).map((item) => item.clerk_user_id) }; }
export async function updateContractResponsible(contractId: string, responsibleClerkUserId: string): Promise<Result> { const context = await getOrganizationContext(); if (context.kind !== "ready" || context.role !== "admin") return { ok: false, message: "계약 담당자 지정은 관리자만 할 수 있습니다." }; const supabase = createSupabaseServerClient(); const { data: member } = await supabase.from("organization_members").select("id").eq("organization_id", context.organizationId).eq("clerk_user_id", responsibleClerkUserId).eq("status", "active").maybeSingle(); if (!member) return { ok: false, message: "현재 조직의 활성 멤버만 담당자로 지정할 수 있습니다." }; const { error } = await supabase.from("contracts").update({ responsible_clerk_user_id: responsibleClerkUserId, updated_by_clerk_user_id: context.clerkUserId }).eq("id", contractId).eq("organization_id", context.organizationId); if (error) return { ok: false, message: "계약 담당자를 저장하지 못했습니다." }; revalidatePath(`/contracts/${contractId}`); revalidatePath("/revenue"); return { ok: true }; }

async function accessibleContract(contractId: string) {
  const context = await getOrganizationContext();
  if (context.kind !== "ready") return { context, contract: null as any };
  const supabase = createSupabaseServerClient();
  const { data: contract } = await supabase.from("contracts").select("id, responsible_clerk_user_id").eq("id", contractId).eq("organization_id", context.organizationId).maybeSingle();
  if (!contract || (context.role !== "admin" && contract.responsible_clerk_user_id !== context.clerkUserId)) return { context, contract: null as any };
  return { context, contract };
}

export async function getContractRevenueDetail(contractId: string): Promise<RevenueDetail | null> {
  const { context, contract } = await accessibleContract(contractId); if (context.kind !== "ready" || !contract) return null;
  const supabase = createSupabaseServerClient();
  const [{ data: settlement }, { data: entries }, { data: rate }] = await Promise.all([supabase.from("contract_revenue_settlements").select("agreed_commission_amount, tenant_commission_amount, landlord_commission_amount, office_share_rate, staff_share_rate, settlement_note").eq("contract_id", contractId).eq("organization_id", context.organizationId).maybeSingle(), supabase.from("contract_revenue_entries").select("id, entry_type, entry_date, gross_amount, external_co_broker_share_amount, office_share_amount, staff_share_amount, office_share_rate, staff_share_rate, memo").eq("contract_id", contractId).eq("organization_id", context.organizationId).order("entry_date", { ascending: false }).order("created_at", { ascending: false }), supabase.from("organization_member_revenue_rates").select("staff_share_rate").eq("organization_id", context.organizationId).eq("clerk_user_id", contract.responsible_clerk_user_id ?? "").maybeSingle()]);
  const mapped = (entries ?? []).map((item) => ({ id: item.id, entryType: item.entry_type as "receipt" | "refund", entryDate: item.entry_date, grossAmount: item.gross_amount, externalAmount: item.external_co_broker_share_amount, officeAmount: item.office_share_amount, staffAmount: item.staff_share_amount, officeRate: Number(item.office_share_rate), staffRate: Number(item.staff_share_rate), memo: item.memo }));
  const received = mapped.filter((item) => item.entryType === "receipt").reduce((sum, item) => sum + item.grossAmount, 0); const refunded = mapped.filter((item) => item.entryType === "refund").reduce((sum, item) => sum + item.grossAmount, 0); const sign = (item: RevenueEntry) => item.entryType === "receipt" ? 1 : -1;
  const defaultStaffRate = Number(rate?.staff_share_rate ?? 50); return { canManage: context.role === "admin" || contract.responsible_clerk_user_id === context.clerkUserId, responsible: contract.responsible_clerk_user_id, defaultOfficeRate: 100 - defaultStaffRate, defaultStaffRate, settlement: settlement ? { tenantCommissionAmount: settlement.tenant_commission_amount, landlordCommissionAmount: settlement.landlord_commission_amount, agreed: settlement.agreed_commission_amount, officeRate: Number(settlement.office_share_rate), staffRate: Number(settlement.staff_share_rate), note: settlement.settlement_note } : null, entries: mapped, received, refunded, outstanding: Math.max(0, (settlement?.agreed_commission_amount ?? 0) - received + refunded), officeNet: mapped.reduce((sum, item) => sum + sign(item) * item.officeAmount, 0), staffNet: mapped.reduce((sum, item) => sum + sign(item) * item.staffAmount, 0) };
}

export async function saveRevenueSettlement(values: RevenueSettlementInput): Promise<Result> {
  const parsed = revenueSettlementSchema.safeParse(values); if (!parsed.success) return { ok: false, message: "정산 기준을 확인해 주세요.", fieldErrors: parsed.error.flatten().fieldErrors };
  const { context, contract } = await accessibleContract(parsed.data.contractId); if (context.kind !== "ready" || !contract) return { ok: false, message: "이 계약의 정산 기준을 저장할 권한이 없습니다." };
  const supabase = createSupabaseServerClient(); const value = parsed.data; const tenant = Number(value.tenantCommissionAmount); const landlord = Number(value.landlordCommissionAmount); const { data: rate } = await supabase.from("organization_member_revenue_rates").select("staff_share_rate").eq("organization_id", context.organizationId).eq("clerk_user_id", contract.responsible_clerk_user_id ?? "").maybeSingle(); const staffRate = Number(rate?.staff_share_rate ?? 50);
  const { error } = await supabase.from("contract_revenue_settlements").upsert({ organization_id: context.organizationId, contract_id: value.contractId, agreed_commission_amount: tenant + landlord, tenant_commission_amount: tenant, landlord_commission_amount: landlord, office_share_rate: 100 - staffRate, staff_share_rate: staffRate, settlement_note: value.settlementNote || null, created_by_clerk_user_id: context.clerkUserId, updated_by_clerk_user_id: context.clerkUserId }, { onConflict: "contract_id" });
  if (error) return { ok: false, message: "정산 기준을 저장하지 못했습니다. Dev DB migration 적용 상태를 확인해 주세요." }; revalidatePath(`/contracts/${value.contractId}`); revalidatePath("/revenue"); return { ok: true };
}

export async function addRevenueEntry(values: RevenueEntryInput): Promise<Result> {
  const parsed = revenueEntrySchema.safeParse(values); if (!parsed.success) return { ok: false, message: "수납 또는 환불 내용을 확인해 주세요.", fieldErrors: parsed.error.flatten().fieldErrors };
  const { context, contract } = await accessibleContract(parsed.data.contractId); if (context.kind !== "ready" || !contract?.responsible_clerk_user_id) return { ok: false, message: "계약 담당자를 확인할 수 없습니다." };
  const value = parsed.data; const supabase = createSupabaseServerClient(); const { data: settlement } = await supabase.from("contract_revenue_settlements").select("office_share_rate, staff_share_rate").eq("contract_id", value.contractId).eq("organization_id", context.organizationId).maybeSingle(); if (!settlement) return { ok: false, message: "먼저 임차인·임대인 수수료 정산을 저장해 주세요." }; const gross = Number(value.grossAmount); const external = 0; const staffAmount = Math.floor(gross * Number(settlement.staff_share_rate) / 100); const officeAmount = gross - staffAmount;
  const { error } = await supabase.from("contract_revenue_entries").insert({ organization_id: context.organizationId, contract_id: value.contractId, responsible_clerk_user_id: contract.responsible_clerk_user_id, entry_type: value.entryType, entry_date: value.entryDate, gross_amount: gross, external_co_broker_share_amount: external, office_share_rate: Number(settlement.office_share_rate), staff_share_rate: Number(settlement.staff_share_rate), office_share_amount: officeAmount, staff_share_amount: staffAmount, memo: value.memo || null, created_by_clerk_user_id: context.clerkUserId, updated_by_clerk_user_id: context.clerkUserId });
  if (error) return { ok: false, message: "수납·환불 기록을 저장하지 못했습니다." }; revalidatePath(`/contracts/${value.contractId}`); revalidatePath("/revenue"); return { ok: true };
}

export async function getMonthlyRevenue(month: string) {
  const context = await getOrganizationContext(); if (context.kind !== "ready") return { context, rows: [] as any[], totals: { staff: 0, office: 0, receipts: 0, refunds: 0 } };
  const supabase = createSupabaseServerClient(); const start = `${month}-01`; const end = `${month}-31`;
  let query = supabase.from("contract_revenue_entries").select("id, contract_id, responsible_clerk_user_id, entry_type, entry_date, gross_amount, office_share_amount, staff_share_amount, contracts!inner(contract_reference_number, listings!inner(listing_reference_number, units!inner(unit_number, buildings!inner(name))))").eq("organization_id", context.organizationId).gte("entry_date", start).lte("entry_date", end).order("entry_date", { ascending: false });
  if (context.role !== "admin") query = query.eq("responsible_clerk_user_id", context.clerkUserId);
  const { data } = await query; const rows = (data ?? []).map((item: any) => { const contract = Array.isArray(item.contracts) ? item.contracts[0] : item.contracts; const listing = Array.isArray(contract?.listings) ? contract.listings[0] : contract?.listings; const unit = Array.isArray(listing?.units) ? listing.units[0] : listing?.units; const building = Array.isArray(unit?.buildings) ? unit.buildings[0] : unit?.buildings; const sign = item.entry_type === "receipt" ? 1 : -1; return { id: item.id, date: item.entry_date, type: item.entry_type, contractId: item.contract_id, contractLabel: `C-${String(contract?.contract_reference_number ?? "").padStart(6, "0")} · ${building?.name ?? "건물"} ${unit?.unit_number ?? "호실"}`, responsible: item.responsible_clerk_user_id, gross: sign * item.gross_amount, office: sign * item.office_share_amount, staff: sign * item.staff_share_amount }; });
  return { context, rows, totals: { receipts: rows.filter((item) => item.type === "receipt").reduce((sum, item) => sum + item.gross, 0), refunds: rows.filter((item) => item.type === "refund").reduce((sum, item) => sum - item.gross, 0), office: rows.reduce((sum, item) => sum + item.office, 0), staff: rows.reduce((sum, item) => sum + item.staff, 0) } };
}
